### ISSUE TITLE
Key Errror: orange_glazed_terracotta

### ISSUE THREAD

**Issue by pmdoll** [zt-yang/ASIST-MC-toolbox#1]
We seem to be missing some files 

```
Creating JSON file for world Falcon
Loading World 'Falcon': 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 26/26 [00:03<00:00,  7.63 Region/s]
28 31 8 12 12 14
cannot find image in resources/myblocks/ orange_glazed_terracotta
cannot find image in resources/myblocks/ white_glazed_terracotta
Traceback (most recent call last):
  File "./testbed_to_json.py", line 48, in <module>
    to_json(world_name)
  File "./testbed_to_json.py", line 32, in to_json
    all_blocks, important_blocks = mg.generate_maps(world, region, ranges)
  File "/Users/prakash/projects/asist-rita/git/ASIST-MC-toolbox/map_generator.py", line 175, in generate_maps
    image_layer.append(join('resources','myblocks',images[stats['block_type']]))
KeyError: 'orange_glazed_terracotta'

```

**Comment by pmdoll** [comment]
Fixed in most recent commit
